### ISSUE TITLE
使用GPU运行失败

### ISSUE THREAD

**Issue by watchworld** [jianchang512/stt#51]
cuda: cuda_11.8.0_522.06_windows
cudnn:cudnn-windows-x86_64-8.9.7.29_cuda11-archive
安装:conda install pytorch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 pytorch-cuda=11.8 -c pytorch -c nvidia
安装后程序问题：parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device
尝试好几个版本都出现这个问题，显卡型号是geforce 940m。

**Comment by jianchang512** [comment]
先卸载  ctranslate2   conda uninstall -y ctranslate2

再重新安装 3.24.0 版本

conda install  ctranslate2==3.24.0

然后安装下cublas https://github.com/jianchang512/stt/releases/tag/v0.0.1

试试

**Comment by watchworld** [comment]
> 先卸载 ctranslate2 conda uninstall -y ctranslate2
> 
> 再重新安装 3.24.0 版本
> 
> conda install ctranslate2==3.24.0
> 
> 然后安装下cublas https://github.com/jianchang512/stt/releases/tag/v0.0.1
> 
> 试试

相配套的faster-whisper是什么版本，本地是1.0.2，需要ctranslate2 4-5版本

**Comment by jianchang512** [comment]
都可以。只是 ctranslate2的>=4 版本不再支持 cuda12以下

**Comment by watchworld** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
faster-whisper 1.0.2 requires ctranslate2<5,>=4.0, but you have ctranslate2 3.24.0 which is incompatible.

**Comment by jianchang512** [comment]
在其他模块都安装好后，先卸载 `pip uninstall -y ctranslate2`

再单独安装 pip install ctranslate2==3.24.0

**Comment by watchworld** [comment]
按上述要求操作已经解决了问题。 @jianchang512
