### ISSUE TITLE
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Rockycocky** [jianchang512/stt#76]
下载的media模型 上传音频正常 转文字的时候报错

{'web_address': '10.10.61.117:9977', 'lang': 'zh', 'devtype': 'cuda', 'cuda_com_type': 'int8', 'beam_size': 1, 'best_of': 1, 'vad': True, 'temperature': 0, 'condition_on_previous_text': False, 'initial_prompt_zh': '以下是普通话内容，请转录为中文简体。'}

浏览器已打开，若未能自动打开，请手动打开网址  http://localhost:9977
res.status_code=200
d={'version': 'v0.0.92', 'version_num': 92}
以下是普通话内容，请转录为中文简体。
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
已放弃 (核心已转储)

**Comment by jianchang512** [comment]
pip install nvidia-cublas-cu11 nvidia-cudnn-cu11

**Comment by Rockycocky** [comment]
sudo apt install libcudnn8 后解决了
